### ISSUE TITLE
Error: 请检查 Cookie 是否正确

### ISSUE THREAD

**Issue by ziyi-joe** [kaluojushi/zju-health-report#1]
昨天起开始报错：Error: 请检查 Cookie 是否正确
看了一下好像是普遍问题

**Comment by kaluojushi** [comment]
> 昨天起开始报错：Error: 请检查 Cookie 是否正确 看了一下好像是普遍问题

是的，已排查出是 Axios 最新版本 1.2.0 的 bug，相关 issue：https://github.com/axios/axios/issues/5298
然后锁定了一下 Axios 的版本，已暂时解决，等 Axios 官方 fix 吧
